version: '3.8'

services:
  backend:
    build: .
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - IMG_MODEL_PATH=models/best_model.h5
      - SENSOR_MODEL_PATH=models/lstm_autoencoder.h5
      - SCALER_PATH=models/lstm_scaler.npy
      - WINDOW_SIZE=30
      - ANOMALY_THRESHOLD=0.001
    volumes:
      - ./models:/app/models
    restart: unless-stopped 